# Auto-generated by Remi.
# Add user-customizations to env_app.rb

require 'bundler/setup'
require 'remi'
require 'remi/cucumber'

require_relative 'env_app.rb'

Remi::Settings.log_level = Logger::ERROR
