# This file was auto-generated by Remi but is expected to be overwritten.
# Put anything in here that should be shared by all jobs.

require 'bundler/setup'
require 'remi'

class AllJobsShared < Remi::Job

  param :sftp do
    {
      host: 'example.com',
      username: 'user',
      password: '1234567890'
    }
  end

  param :salesforce_credentials do
    {
      host: 'login.salesforce.com',
      username: 'user@example.com',
      password: 'password',
      security_token: '4342jn3j4n32n4',
      client_id: 'dkfjsdkfjoasdjdf',
      client_secret: '28357245723475',
      instance_url: 'https://na1.salesforce.com'
    }
  end
end
